import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FileText, Download, CheckCircle2, AlertTriangle, Clock, Scale, Shield, ShieldCheck, Loader2 } from 'lucide-react'
import { useApp, CASE_STATUS } from '../../context/AppContextSimplified'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const formatCurrency = (amount) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount)
const formatTime = (iso) => new Date(iso).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
const formatDate = (iso) => new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })

const ComplianceWorkspace = () => {
  const { getCasesByStatus, finalizeRestriction } = useApp()
  const [selectedReviewCase, setSelectedReviewCase] = useState(null)
  const [finalizingId, setFinalizingId] = useState(null)
  const [toastMessage, setToastMessage] = useState('')

  // Isolated export loading states — NEVER mutate global case status
  const [isGeneratingSAR, setIsGeneratingSAR] = useState(false)
  const [sarGenerated, setSarGenerated] = useState(false)
  const [isGeneratingDPIP, setIsGeneratingDPIP] = useState(false)
  const [dpipGenerated, setDpipGenerated] = useState(false)

  const pendingReview = getCasesByStatus(CASE_STATUS.AWAITING_LEGAL_REVIEW)

  // Reset export states when selected case changes
  useEffect(() => {
    setSarGenerated(false)
    setDpipGenerated(false)
    setIsGeneratingSAR(false)
    setIsGeneratingDPIP(false)
  }, [selectedReviewCase?.id])

  // Auto-deselect if the selected case leaves the pending review list (was finalized)
  useEffect(() => {
    if (selectedReviewCase && !pendingReview.find(c => c.id === selectedReviewCase.id)) {
      setSelectedReviewCase(null)
    }
  }, [pendingReview, selectedReviewCase])

  const showToast = (msg) => {
    setToastMessage(msg)
    setTimeout(() => setToastMessage(''), 3000)
  }

  const getTimeline = (caseItem) => [
    { time: formatTime(caseItem.timestamp), event: 'Alert generated by anomaly detection', icon: AlertTriangle, status: 'completed' },
    { time: formatTime(new Date(new Date(caseItem.timestamp).getTime() + 4000)), event: 'Transaction trace completed', icon: Shield, status: 'completed' },
    { time: formatTime(new Date(new Date(caseItem.timestamp).getTime() + 120000)), event: `Partial lien approved by ${caseItem.analystName || 'Analyst'}`, icon: CheckCircle2, status: 'completed' },
    { time: 'Now', event: 'Awaiting legal authorization', icon: Clock, status: 'active' }
  ]

  // Double-click safe: disable while processing
  const isAnyActionProcessing = isGeneratingSAR || isGeneratingDPIP || finalizingId !== null

  const handleFinalize = (caseId) => {
    if (isAnyActionProcessing) return
    setFinalizingId(caseId)
    setTimeout(() => {
      finalizeRestriction(caseId)
      setFinalizingId(null)
      setSelectedReviewCase(null)
      showToast('Restriction authorized and active')
    }, 800)
  }

  // SAR generation — local loading state only, panel stays visible
  const handleGenerateSAR = (caseItem) => {
    if (isAnyActionProcessing || !caseItem) return
    setIsGeneratingSAR(true)
    setTimeout(() => {
      generateSARPdf(caseItem)
      setIsGeneratingSAR(false)
      setSarGenerated(true)
      showToast('SAR PDF generated successfully')
    }, 1000)
  }

  // DPIP generation — local loading state only, panel stays visible
  const handleGenerateDPIP = (caseItem) => {
    if (isAnyActionProcessing || !caseItem) return
    setIsGeneratingDPIP(true)
    setTimeout(() => {
      generateDPIPPdf(caseItem)
      setIsGeneratingDPIP(false)
      setDpipGenerated(true)
      showToast('DPIP interbank packet exported')
    }, 1000)
  }

  // --- PDF Generation (pure side-effect, no state mutation) ---

  const generateSARPdf = (c) => {
    const doc = new jsPDF()
    let y = 20
    doc.setFontSize(16); doc.setFont('helvetica', 'bold')
    doc.text('SUSPICIOUS ACTIVITY REPORT (SAR)', 20, y); y += 12
    doc.setFontSize(9); doc.setFont('helvetica', 'normal')
    doc.text(`Generated: ${new Date().toISOString()}`, 20, y); y += 6
    doc.text(`Case ID: ${c.id}`, 20, y); y += 6
    doc.text(`Priority: ${c.priority}`, 20, y); y += 12
    doc.setFontSize(12); doc.setFont('helvetica', 'bold')
    doc.text('Case Summary', 20, y); y += 8
    doc.setFontSize(10); doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(c.aiSummary, 170)
    doc.text(lines, 20, y); y += lines.length * 5 + 8
    doc.setFontSize(12); doc.setFont('helvetica', 'bold')
    doc.text('Containment Action', 20, y); y += 8
    autoTable(doc, { startY: y, head: [['Field', 'Value']], body: [['Customer', c.customerName], ['Risk Amount', formatCurrency(c.riskAmount)], ['Traced Amount', formatCurrency(c.tracedAmount)], ['Action', 'Partial Lien (Proportional Hold)'], ['Approved By', c.analystName || 'Analyst'], ['Mule Accounts', c.muleAccounts.join(', ')], ['Merchant Accounts', c.merchantAccounts.join(', ')]], margin: { left: 20, right: 20 }, styles: { fontSize: 9 } })
    y = doc.lastAutoTable.finalY + 12
    doc.setFontSize(12); doc.setFont('helvetica', 'bold')
    doc.text('Audit Timeline', 20, y); y += 8
    autoTable(doc, { startY: y, head: [['Time', 'Event']], body: getTimeline(c).map(e => [e.time, e.event]), margin: { left: 20, right: 20 }, styles: { fontSize: 9 } })
    y = doc.lastAutoTable.finalY + 12
    doc.setFontSize(8); doc.setFont('helvetica', 'normal')
    const hash = Array.from({ length: 64 }, () => '0123456789abcdef'[Math.floor(Math.random() * 16)]).join('')
    doc.text(`Integrity Hash (SHA-256): ${hash}`, 20, y)
    doc.save(`SAR-${c.id}.pdf`)
  }

  const generateDPIPPdf = (c) => {
    const doc = new jsPDF()
    let y = 20
    doc.setFontSize(16); doc.setFont('helvetica', 'bold')
    doc.text('DPIP INTERBANK CONTAINMENT PACKET', 20, y); y += 12
    doc.setFontSize(9); doc.setFont('helvetica', 'normal')
    doc.text(`Generated: ${new Date().toISOString()}`, 20, y); y += 6
    doc.text(`Case Reference: ${c.id}`, 20, y); y += 6
    doc.text('Status: DPIP Coordinated', 20, y); y += 12
    autoTable(doc, { startY: y, head: [['Field', 'Value']], body: [['Case ID', c.id], ['Traced Amount', formatCurrency(c.tracedAmount)], ['Affected Accounts', String(c.muleAccounts.length + c.merchantAccounts.length)], ['Recommended Action', 'Partial Restriction'], ['Summary', c.aiSummary]], margin: { left: 20, right: 20 }, styles: { fontSize: 9 } })
    y = doc.lastAutoTable.finalY + 10
    doc.setFontSize(12); doc.setFont('helvetica', 'bold')
    doc.text('Freeze Instructions', 20, y); y += 8
    const freezeData = c.muleAccounts.map(acc => [acc, formatCurrency(c.tracedAmount / c.muleAccounts.length), 'Proportional Lien'])
    autoTable(doc, { startY: y, head: [['Account Number', 'Amount', 'Hold Type']], body: freezeData, margin: { left: 20, right: 20 }, styles: { fontSize: 9 } })
    doc.save(`DPIP-${c.id}.pdf`)
  }

  // --- RENDER ---

  return (
    <div className="h-full w-full flex flex-col overflow-hidden bg-slate-950">
      {/* Toast */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="fixed top-4 right-4 z-50 px-4 py-2.5 bg-emerald-500/90 text-white text-sm font-semibold rounded-xl shadow-lg shadow-emerald-500/20 backdrop-blur">
            <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4" />{toastMessage}</div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Header */}
      <div className="px-6 py-4 border-b border-slate-800/50 bg-slate-900/30">
        <div className="flex items-center gap-3">
          <Scale className="w-5 h-5 text-slate-400" />
          <div>
            <h1 className="text-sm font-bold text-slate-200 tracking-wide">COMPLIANCE REVIEW</h1>
            <p className="text-[11px] text-slate-500 mt-0.5">{pendingReview.length} case{pendingReview.length !== 1 ? 's' : ''} awaiting legal authorization</p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left — Table + Export */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5 border-r border-slate-800/30">
          <div className="space-y-3">
            <h2 className="text-[10px] font-bold text-slate-400 tracking-widest">PENDING REVIEWS</h2>
            <AnimatePresence mode="popLayout">
              {pendingReview.length === 0 ? (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-12 text-slate-600">
                  <CheckCircle2 className="w-8 h-8 mx-auto mb-2 opacity-30" />
                  <p className="text-xs">No cases awaiting review</p>
                </motion.div>
              ) : (
                <div className="rounded-xl border border-slate-800/50 overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-slate-900/50 border-b border-slate-800/50">
                      <tr>
                        <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 tracking-wider">Case ID</th>
                        <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 tracking-wider">Customer</th>
                        <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 tracking-wider">Amount</th>
                        <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 tracking-wider">Analyst</th>
                        <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 tracking-wider">Time</th>
                        <th className="px-4 py-3 text-center text-[10px] font-bold text-slate-500 tracking-wider">Action</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/30">
                      {pendingReview.map(caseItem => (
                        <motion.tr key={caseItem.id} layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, x: -100 }} onClick={() => setSelectedReviewCase(caseItem)} className={`cursor-pointer transition-colors ${selectedReviewCase?.id === caseItem.id ? 'bg-cyan-500/5' : 'hover:bg-slate-900/50'}`}>
                          <td className="px-4 py-3 font-mono text-[11px] text-slate-400">{caseItem.id}</td>
                          <td className="px-4 py-3 text-xs font-semibold text-slate-300">{caseItem.customerName}</td>
                          <td className="px-4 py-3 font-mono text-xs font-bold text-slate-200">{formatCurrency(caseItem.tracedAmount)}</td>
                          <td className="px-4 py-3 text-xs text-slate-500">{caseItem.analystName || '—'}</td>
                          <td className="px-4 py-3 text-[11px] text-slate-500">{formatDate(caseItem.timestamp)}</td>
                          <td className="px-4 py-3 text-center">
                            <motion.button onClick={(e) => { e.stopPropagation(); handleFinalize(caseItem.id) }} whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }} disabled={isAnyActionProcessing} className={`px-3 py-1.5 rounded-lg font-bold text-[11px] transition-all ${finalizingId === caseItem.id ? 'bg-emerald-500/20 text-emerald-400 opacity-50 cursor-not-allowed' : isAnyActionProcessing ? 'opacity-50 cursor-not-allowed bg-slate-700/50 text-slate-500' : 'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 border border-emerald-500/20'}`}>
                              {finalizingId === caseItem.id ? 'Authorizing...' : 'Authorize'}
                            </motion.button>
                          </td>
                        </motion.tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </AnimatePresence>
          </div>
        </div>

        {/* Right — Case Governance Panel */}
        <div className="w-[340px] flex-shrink-0 overflow-y-auto p-5 hidden lg:block">
          {selectedReviewCase ? (
            <motion.div key={selectedReviewCase.id} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="space-y-5">
              <div>
                <h3 className="text-xs font-bold text-slate-300 mb-1">{selectedReviewCase.customerName}</h3>
                <p className="text-[10px] text-slate-500 font-mono">{selectedReviewCase.id}</p>
              </div>
              <div className="p-3 rounded-xl bg-slate-900/50 border border-slate-800/30">
                <p className="text-xs text-slate-400 leading-relaxed">{selectedReviewCase.aiSummary}</p>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-xs"><span className="text-slate-500">Risk Amount</span><span className="font-mono font-bold text-slate-300">{formatCurrency(selectedReviewCase.riskAmount)}</span></div>
                <div className="flex justify-between text-xs"><span className="text-slate-500">Traced (Lien)</span><span className="font-mono font-bold text-amber-400">{formatCurrency(selectedReviewCase.tracedAmount)}</span></div>
                <div className="flex justify-between text-xs border-t border-slate-800/50 pt-2"><span className="text-slate-500">Action</span><span className="text-xs font-semibold text-emerald-400">Partial Lien (Recommended)</span></div>
              </div>

              {/* Audit Timeline */}
              <div className="space-y-3">
                <h3 className="text-[10px] font-bold text-slate-400 tracking-widest">AUDIT TIMELINE</h3>
                <div className="space-y-0">
                  {getTimeline(selectedReviewCase).map((event, idx) => {
                    const IconComp = event.icon
                    const isActive = event.status === 'active'
                    const isCompleted = event.status === 'completed'
                    const timeline = getTimeline(selectedReviewCase)
                    return (
                      <div key={idx} className="flex gap-3">
                        <div className="flex flex-col items-center">
                          <div className={`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 ${isCompleted ? 'bg-emerald-500/15' : isActive ? 'bg-amber-500/15' : 'bg-slate-800'}`}>
                            <IconComp className={`w-3.5 h-3.5 ${isCompleted ? 'text-emerald-400' : isActive ? 'text-amber-400' : 'text-slate-500'}`} />
                          </div>
                          {idx < timeline.length - 1 && <div className={`w-px h-8 ${isCompleted ? 'bg-emerald-500/20' : 'bg-slate-800'}`} />}
                        </div>
                        <div className="pb-3 pt-0.5">
                          <p className="text-[10px] font-mono text-slate-600">{event.time}</p>
                          <p className={`text-xs mt-0.5 ${isActive ? 'text-amber-400 font-semibold' : 'text-slate-400'}`}>{event.event}</p>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>

              {/* Export Center (Strictly tied to selectedCase) */}
              <div className="space-y-3 pt-2 border-t border-slate-800/50">
                <h2 className="text-[10px] font-bold text-slate-400 tracking-widest">EXPORT CENTER</h2>
                <div className="flex gap-2">
                  {/* SAR Button */}
                  <motion.button
                    onClick={() => handleGenerateSAR(selectedReviewCase)}
                    whileHover={!isAnyActionProcessing && !sarGenerated ? { scale: 1.02 } : {}}
                    whileTap={!isAnyActionProcessing && !sarGenerated ? { scale: 0.98 } : {}}
                    disabled={isAnyActionProcessing || sarGenerated}
                    className={`flex-1 px-3 py-2.5 rounded-xl border transition-all ${sarGenerated ? 'border-emerald-500/30 bg-emerald-500/5' : isGeneratingSAR ? 'border-slate-700/50 bg-slate-900/50 opacity-50 cursor-not-allowed' : 'border-slate-700/50 bg-slate-900/50 hover:bg-slate-800/50'}`}
                  >
                    <div className="flex items-center gap-1.5 mb-0.5">
                      {isGeneratingSAR ? <Loader2 className="w-3.5 h-3.5 text-cyan-400 animate-spin" /> : sarGenerated ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <FileText className="w-3.5 h-3.5 text-cyan-400" />}
                      <span className={`text-[11px] font-bold ${sarGenerated ? 'text-emerald-400' : 'text-slate-300'}`}>{isGeneratingSAR ? 'Generating...' : sarGenerated ? 'SAR ✓' : 'SAR PDF'}</span>
                    </div>
                  </motion.button>

                  {/* DPIP Button */}
                  <motion.button
                    onClick={() => handleGenerateDPIP(selectedReviewCase)}
                    whileHover={!isAnyActionProcessing && !dpipGenerated ? { scale: 1.02 } : {}}
                    whileTap={!isAnyActionProcessing && !dpipGenerated ? { scale: 0.98 } : {}}
                    disabled={isAnyActionProcessing || dpipGenerated}
                    className={`flex-1 px-3 py-2.5 rounded-xl border transition-all ${dpipGenerated ? 'border-emerald-500/30 bg-emerald-500/5' : isGeneratingDPIP ? 'border-slate-700/50 bg-slate-900/50 opacity-50 cursor-not-allowed' : 'border-slate-700/50 bg-slate-900/50 hover:bg-slate-800/50'}`}
                  >
                    <div className="flex items-center gap-1.5 mb-0.5">
                      {isGeneratingDPIP ? <Loader2 className="w-3.5 h-3.5 text-amber-400 animate-spin" /> : dpipGenerated ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <Download className="w-3.5 h-3.5 text-amber-400" />}
                      <span className={`text-[11px] font-bold ${dpipGenerated ? 'text-emerald-400' : 'text-slate-300'}`}>{isGeneratingDPIP ? 'Exporting...' : dpipGenerated ? 'DPIP ✓' : 'DPIP Packet'}</span>
                    </div>
                  </motion.button>
                </div>
              </div>

              {/* Finalize Button — disabled while exporting */}
              <motion.button
                onClick={() => handleFinalize(selectedReviewCase.id)}
                whileHover={!isAnyActionProcessing ? { scale: 1.01 } : {}}
                whileTap={!isAnyActionProcessing ? { scale: 0.98 } : {}}
                disabled={isAnyActionProcessing}
                className={`w-full py-3 bg-gradient-to-r from-emerald-600 to-emerald-500 text-white font-bold rounded-xl text-sm flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/15 transition-all ${isAnyActionProcessing ? 'opacity-50 cursor-not-allowed' : ''}`}
              >
                <ShieldCheck className="w-4 h-4" />
                {finalizingId === selectedReviewCase.id ? 'Authorizing...' : 'Authorize & Finalize Restriction'}
              </motion.button>
              <p className="text-center text-[10px] text-slate-600">Restriction will become active for branch operations</p>
            </motion.div>
          ) : (
            <div className="h-full flex items-center justify-center">
              <div className="text-center text-slate-600">
                <Scale className="w-8 h-8 mx-auto mb-2 opacity-20" />
                <p className="text-[10px]">Select a case to view governance details</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default ComplianceWorkspace
