import { motion, AnimatePresence } from 'framer-motion'
import { FileText, Download, CheckCircle2, AlertTriangle, Clock } from 'lucide-react'
import { useApp, CASE_STATUS } from '../../context/AppContextSimplified'
import jsPDF from 'jspdf'
import 'jspdf-autotable'

const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0
  }).format(amount)
}

const formatTime = (isoString) => {
  const date = new Date(isoString)
  return date.toLocaleTimeString('en-IN')
}

const ComplianceWorkspace = ({ activeView }) => {
  const { getCasesByStatus, resolveCase } = useApp()

  const pendingReview = getCasesByStatus(CASE_STATUS.AWAITING_LEGAL_REVIEW)

  // Timeline events for audit trail
  const timelineEvents = [
    { time: '14:02:11', event: 'Alert generated by ML', icon: AlertTriangle, color: 'red', status: 'completed' },
    { time: '14:02:15', event: 'Transaction trace completed', icon: CheckCircle2, color: 'cyan', status: 'completed' },
    { time: '14:04:10', event: 'Partial lien approved by Analyst', icon: AlertTriangle, color: 'emerald', status: 'completed' },
    { time: '14:04:45', event: 'Awaiting Legal Review', icon: Clock, color: 'amber', status: 'active' }
  ]

  // Export handlers
  const handleExport = (caseId, type) => {
    const doc = new jsPDF()
    const pageHeight = doc.internal.pageSize.getHeight()
    const pageWidth = doc.internal.pageSize.getWidth()
    let yPosition = 20

    if (type === 'fir') {
      doc.setFontSize(16)
      doc.text('FIR EVIDENCE BUNDLE', 20, yPosition)
      yPosition += 15

      doc.setFontSize(10)
      doc.text([
        `Case ID: ${caseId}`,
        `Generated: ${new Date().toISOString()}`,
        `Status: Ready for submission`
      ], 20, yPosition)

      yPosition += 30
      doc.setFontSize(12)
      doc.text('Evidence Package Contents:', 20, yPosition)
      yPosition += 10

      const tableData = [
        ['Transaction Hash', 'Amount', 'Network Path'],
        ['HASH-001', '₹70,000', 'Victim → Mule → Merchant'],
        ['HASH-002', '₹65,000', 'Victim → Mule → Merchant'],
        ['HASH-003', '₹65,000', 'Victim → Mule → Merchant']
      ]

      doc.autoTable({
        startY: yPosition,
        head: [tableData[0]],
        body: tableData.slice(1),
        margin: { top: 20, right: 20, bottom: 20, left: 20 }
      })
    } else {
      doc.setFontSize(16)
      doc.text('INTERBANK FREEZE PACKET', 20, yPosition)
      yPosition += 15

      doc.setFontSize(10)
      doc.text([
        `Case ID: ${caseId}`,
        `Generated: ${new Date().toISOString()}`,
        `Status: DPIP Coordinated`
      ], 20, yPosition)

      yPosition += 30
      doc.setFontSize(12)
      doc.text('Freeze Instructions:', 20, yPosition)
      yPosition += 10

      const tableData = [
        ['Account Number', 'Amount', 'Hold Type'],
        ['185502000087321', '₹70,000', 'Proportional Lien'],
        ['039405001234567', '₹65,000', 'Proportional Lien'],
        ['602305001987654', '₹65,000', 'Proportional Lien']
      ]

      doc.autoTable({
        startY: yPosition,
        head: [tableData[0]],
        body: tableData.slice(1),
        margin: { top: 20, right: 20, bottom: 20, left: 20 }
      })
    }

    doc.save(`${type}-${caseId}.pdf`)
  }

  return (
    <div className="h-full w-full flex flex-col overflow-hidden bg-white rounded-lg border">
      {/* Header */}
      <div className="px-6 py-4 border-b bg-slate-50">
        <h1 className="text-lg font-bold text-slate-900">COMPLIANCE REVIEW</h1>
        <p className="text-sm text-slate-600 mt-1">{pendingReview.length} cases awaiting legal approval</p>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {/* Pending Reviews Table */}
        <div className="space-y-3">
          <h2 className="text-sm font-bold text-slate-900">PENDING REVIEWS</h2>

          <AnimatePresence>
            {pendingReview.length === 0 ? (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="text-center py-8 text-slate-500"
              >
                <p className="text-sm">No cases awaiting review</p>
              </motion.div>
            ) : (
              <div className="border rounded-lg overflow-hidden">
                <table className="w-full text-sm">
                  <thead className="bg-slate-50 border-b">
                    <tr>
                      <th className="px-4 py-3 text-left font-semibold text-slate-900">Case ID</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-900">Amount</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-900">Action</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-900">Submitted</th>
                      <th className="px-4 py-3 text-center font-semibold text-slate-900">Approve</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {pendingReview.map(caseItem => (
                      <motion.tr
                        key={caseItem.id}
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="hover:bg-slate-50"
                      >
                        <td className="px-4 py-3 font-mono text-xs text-slate-700">{caseItem.id}</td>
                        <td className="px-4 py-3 font-bold text-slate-900">{formatCurrency(caseItem.riskAmount)}</td>
                        <td className="px-4 py-3 text-slate-700">Partial Lien (Recommended)</td>
                        <td className="px-4 py-3 text-xs text-slate-600">{formatTime(caseItem.timestamp)}</td>
                        <td className="px-4 py-3 text-center">
                          <motion.button
                            onClick={() => resolveCase(caseItem.id)}
                            whileHover={{ scale: 1.05 }}
                            whileTap={{ scale: 0.95 }}
                            className="px-3 py-1 bg-emerald-100 text-emerald-700 rounded font-semibold text-xs hover:bg-emerald-200"
                          >
                            Approve
                          </motion.button>
                        </td>
                      </motion.tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </AnimatePresence>
        </div>

        {/* Audit Timeline */}
        <div className="space-y-3">
          <h2 className="text-sm font-bold text-slate-900">AUDIT TIMELINE</h2>

          <div className="space-y-2">
            {timelineEvents.map((event, idx) => {
              const IconComponent = event.icon
              const isActive = event.status === 'active'
              const isCompleted = event.status === 'completed'

              return (
                <div key={idx} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                      isCompleted ? 'bg-emerald-100' :
                      isActive ? 'bg-amber-100' :
                      'bg-slate-100'
                    }`}>
                      <IconComponent className={`w-4 h-4 ${
                        isCompleted ? 'text-emerald-600' :
                        isActive ? 'text-amber-600' :
                        'text-slate-400'
                      }`} />
                    </div>
                    {idx < timelineEvents.length - 1 && (
                      <div className="w-0.5 h-12 bg-slate-200 mt-1" />
                    )}
                  </div>
                  <div className="pb-4">
                    <p className="text-xs font-mono text-slate-500">{event.time}</p>
                    <p className="text-sm font-semibold text-slate-900 mt-1">{event.event}</p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Export Center */}
        {pendingReview.length > 0 && (
          <div className="space-y-3">
            <h2 className="text-sm font-bold text-slate-900">EXPORT CENTER</h2>

            <div className="flex gap-3">
              <motion.button
                onClick={() => handleExport(pendingReview[0].id, 'fir')}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="px-4 py-2 border border-slate-300 rounded-lg text-slate-700 font-semibold text-sm hover:bg-slate-50"
              >
                <FileText className="w-4 h-4 inline mr-2" />
                Generate FIR Bundle
              </motion.button>

              <motion.button
                onClick={() => handleExport(pendingReview[0].id, 'interbank')}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="px-4 py-2 border border-slate-300 rounded-lg text-slate-700 font-semibold text-sm hover:bg-slate-50"
              >
                <Download className="w-4 h-4 inline mr-2" />
                Export Freeze Packet
              </motion.button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default ComplianceWorkspace
