-- Flyway V1: Alert log table
-- Portable SQL — works on both H2 and PostgreSQL

CREATE TABLE IF NOT EXISTS alert_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(128) NOT NULL,
    priority VARCHAR(4) NOT NULL,
    risk_score DOUBLE PRECISION NOT NULL,
    trigger_reason VARCHAR(512) NOT NULL,
    event_timestamp BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alert_log_account ON alert_log(account_id);
CREATE INDEX idx_alert_log_priority ON alert_log(priority);
